//Benjamin Werner 4705456

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "info.h"


//Printing flags
    //-l
    int lexflag = 0;
    //-a
    int codegenflag = 0;
    //-v
    int vmflag = 0;

//main, find the printing flags and start the process
int main(int inputLength, char *inputStringArr[]) {


    char** temp = inputStringArr;

    //Parse through the stringArray and find any flags
    while (inputLength > 1) {
        if (strcmp(temp[1], "-l") == 0)
            lexflag = 1;

        if (strcmp(temp[1], "-a") == 0)
            codegenflag = 1;

        if (strcmp(temp[1], "-v") == 0)
            vmflag = 1;

        inputLength--;
        temp++;
    }

    compile();
}

//visit every files' "main function", performing their tasks
void compile() {

    //For printing purposes
    int character;
    FILE * ifp;

    //Run lex() from lex.c and print to console if appropriate (by flag)
    lex();
    if (lexflag == 1){
        character = 10;
        ifp =  fopen("lexdebug.txt", "r");

        printf("Printing Lex Info....\n");

        while(character != EOF){
            printf("%c", character);
            character = fgetc(ifp);
        }
    }

    //Run parse() from parse.c and print to console if appropriate (by flag)
    parse();
    if (codegenflag == 1){
        character = 10;
        ifp =  fopen("parseroutput.txt", "r");

        printf("\n\nSyntactically correct!\nPrinting CodeGen Info....\n");

        while(character != EOF){
            printf("%c", character);
            character = fgetc(ifp);
        }

        printf("\n\n");
    }

    //run vm() from vm.c printing to console is done within the file.
    vm(vmflag);

    printf("\n\n Success!\n-------File Info-------\ninput.txt: original code file\nlexDebug.txt: Full Lexeme output-Source Program, Lexeme Table, Lexeme List\n");
    printf("lexoutput.txt: Just the lexeme list, used internally\nparseroutput.txt: assembly code generated by parser.c\n");
    printf("vmoutput.txt: Interpreted Assembly Language and program execution\n\n");


}
